name: jesski-desktop
services:
- name: web
  source_dir: /
  github:
    repo: itsjesski/jesski-site-desktop
    branch: main
  
  # Use production build script that sets NODE_ENV
  build_command: npm ci && npm run build:prod
  run_command: npm run start:express
  
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  
  # Optimized health check
  health_check:
    http_path: /api/health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  
  routes:
  - path: /
  
  # Build optimization environment variables
  envs:
  - key: NODE_ENV
    value: production
  - key: NODE_OPTIONS
    value: --max-old-space-size=4096
  - key: GENERATE_SOURCEMAP
    value: false
  - key: DISABLE_ESLINT_PLUGIN
    value: true
  - key: VITE_BUILD_SOURCEMAP
    value: false
  - key: VITE_TWITCH_CHANNEL
    value: jesski
  - key: VITE_API_BASE_URL
    value: ${APP_URL}
